version: 0.2

phases:
        install:
            runtime-versions:
                nodejs: 8
        build:
                commands:
                        - echo "Nothing to do yet"
artifacts:
        files:
                - index.html
                - favicon.ico
                - Resume1.0.pdf
                - styles/main.css
                - images/*
